import { useCallback, useEffect, useRef, useState } from 'react';
import CommunityGuidelines from './legal/CommunityGuidelines.jsx';
import PrivacyPolicy from './legal/PrivacyPolicy.jsx';
import RecordingAgreement from './legal/RecordingAgreement.jsx';
import TermsOfService from './legal/TermsOfService.jsx';

const STEPS=[{id:'terms',label:'Terms of Service',Component:TermsOfService},{id:'privacy',label:'Privacy Policy',Component:PrivacyPolicy},{id:'community',label:'Community Guidelines',Component:CommunityGuidelines},{id:'recording',label:'Recording Agreement',Component:RecordingAgreement}];
const END=48,DEPTH=120,SHORT=8;

function DocumentIcon(){return <svg className="signup-policy-doc-icon" viewBox="0 0 24 28" aria-hidden="true"><path d="M4 1h11l5 5v21H4V1Z"/><path d="M15 1v6h5M8 13h8M8 18h8"/></svg>}
function LockIcon(){return <svg className="signup-policy-lock-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></svg>}

export default function SignupLegalReview({onComplete}){
 const [index,setIndex]=useState(0),[max,setMax]=useState(0),[atEnd,setAtEnd]=useState(false),[seconds,setSeconds]=useState(0),[needsScroll,setNeedsScroll]=useState(true),[agreed,setAgreed]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[completed,setCompleted]=useState(()=>new Set()); const ref=useRef(null),started=useRef(Date.now()); const step=STEPS[index],Doc=step.Component,last=index===3;
 const measure=useCallback(()=>{const el=ref.current;if(!el)return;setNeedsScroll(el.scrollHeight-el.clientHeight>END);setMax(v=>Math.max(v,el.scrollTop));setAtEnd(el.scrollHeight-el.clientHeight-el.scrollTop<=END)},[]);
 useEffect(()=>{const el=ref.current;if(!el)return;el.scrollTop=0;setMax(0);setAtEnd(false);setSeconds(0);setAgreed(false);started.current=Date.now();const scroll=()=>measure();el.addEventListener('scroll',scroll,{passive:true});const ro=new ResizeObserver(()=>requestAnimationFrame(measure));ro.observe(el);requestAnimationFrame(measure);return()=>{el.removeEventListener('scroll',scroll);ro.disconnect()}},[index,mobileOpen,measure]);
 useEffect(()=>{const timer=setInterval(()=>setSeconds(Math.floor((Date.now()-started.current)/1000)),500);return()=>clearInterval(timer)},[index]);
 const read=needsScroll?(max>=DEPTH&&atEnd):seconds>=SHORT,can=read&&agreed;
 const hint=read?'Reading complete. Check the agreement below to continue.':needsScroll?(max<DEPTH?'Scroll through the entire document to continue.':'Scroll to the very end of this document to continue.'):`Please read this document (${Math.max(0,SHORT-seconds)}s remaining).`;
 const mobile=window.matchMedia('(max-width: 600px)').matches;
 const openMobileDocument=i=>{if(!mobile)return;setIndex(i);setMobileOpen(true)};
 const closeMobileDocument=()=>setMobileOpen(false);
 const next=()=>{if(!can)return;if(mobile){const updated=new Set(completed);updated.add(step.id);setCompleted(updated);setMobileOpen(false);if(updated.size===STEPS.length)onComplete();return}if(last)onComplete();else setIndex(i=>i+1)};
 return <section className="signup-legal-review"><aside className="signup-policy-sidebar"><p>Review our policies</p><h2>All debate starts<br/>with respect.</h2><span>Creating a Hot Take account requires reading all four policies in full. You cannot skip this step.</span><ol>{STEPS.map((s,i)=>{const done=completed.has(s.id)||(!mobile&&i<index);return <li key={s.id} className={`${i===index&&(!mobile||mobileOpen)?'active ':''}${done?'completed':''}`}><button type="button" className="signup-policy-select" onClick={()=>openMobileDocument(i)}><DocumentIcon/><b>{i+1}. {s.label}</b><small>{done?'Completed':'Required reading'}</small><i aria-hidden="true"/></button></li>})}</ol><p className="signup-policy-mobile-help">Tap each document to review and check it off.</p><footer><LockIcon/><span>Your progress is saved<br/>as you go.</span></footer></aside><div className={`signup-policy-main${mobileOpen?' signup-policy-main--mobile-open':''}`}><button type="button" className="signup-policy-mobile-close" onClick={closeMobileDocument} aria-label="Close legal document">×</button><div className="signup-legal-review__progress">{STEPS.map((s,i)=><span key={s.id} className={`${completed.has(s.id)||(!mobile&&i<index)?'signup-legal-review__progress-dot--done ':''}${i===index?'signup-legal-review__progress-dot--active':''}`}>{i+1}</span>)}</div><header className="signup-legal-review__header"><p className="signup-legal-review__step">Step {index+1} of 4</p><h3 className="signup-legal-review__title">{step.label}</h3><p className="signup-legal-review__hint">You must read this policy in full before continuing.</p></header><div ref={ref} className="signup-legal-review__scroll" tabIndex={0} role="region" aria-label={`${step.label} scroll to read`}><Doc embedded/></div><footer className="signup-legal-review__footer"><p className="signup-legal-review__scroll-hint"><LockIcon/>{hint}</p><label className="signup-policy-agree"><input type="checkbox" checked={agreed} disabled={!read} onChange={e=>setAgreed(e.target.checked)}/><span>I have read this document in full and agree to the {step.label}.</span></label><button type="button" className="btn btn-primary signup-legal-review__continue" disabled={!can} onClick={next}>{mobile?'Check off document':last?'Continue to create account':'Continue to next policy'}</button></footer></div></section>
}
