import { HotTakeWordmark, IconInstagram, IconReddit, IconShield, IconUser, IconVideo, IconX, IconYouTube } from './LandingAssets.jsx';
import HeaderNavMenu from './HeaderNavMenu.jsx';
import { contactEmailLabel, contactEmailMailto } from './legal/contactEmail.js';
import './SupportPage.css';
import './SupportLayoutFix.css';

const items=[['video','Camera or microphone not working?','Allow camera and microphone in your browser (lock icon in the address bar). On Windows, also check Settings → Privacy → Camera / Microphone and allow your browser. If you have no camera, you can still join with audio only — you should still hear your opponent and see their video when they have a camera.'],['shield','Safety during a debate','If something goes wrong while you are matched with someone, use Report issue on the debate screen. Reports are reviewed by our team and help keep the community safe.'],['user','Account & privacy','For terms, privacy, and community rules, open Menu in the header. Privacy requests (access, deletion, etc.) can also be sent to the contact email above.'],['tool','Technical issues','Try refreshing the page, clearing your cache, or using another browser. If the problem continues, contact us with details about what happened.'],['question','General questions','Check out our FAQ for answers to the most common questions about Hot Take.']];
function SupportIcon({type}){if(type==='video')return <IconVideo/>;if(type==='shield')return <IconShield/>;if(type==='user')return <IconUser/>;if(type==='tool')return <svg viewBox="0 0 32 32"><path d="M19 5a7 7 0 0 0-8 9L3 22a3 3 0 0 0 4 4l8-8a7 7 0 0 0 9-8l-5 5-4-1-1-4 5-5Z"/></svg>;return <svg viewBox="0 0 32 32"><path d="M11 11a5 5 0 1 1 8 4c-2 1-3 2-3 5M16 25h.01"/></svg>}
export default function SupportPage({onBack,isSignedIn,onSignIn,onSignUp,onSignOut,onProfile,onPickLegal,onPickMission,onPickFaq}){const email=contactEmailLabel(),mailto=contactEmailMailto();return <div className="faq-page support-page"><header className="faq-nav"><button onClick={onBack}><HotTakeWordmark variant="nav"/></button><nav><button onClick={onBack}>How it works</button><button onClick={onPickMission}>About</button><button onClick={onBack}>Topics</button><button onClick={onPickFaq}>FAQ</button></nav><div>{isSignedIn?<><button className="faq-pill" onClick={onProfile}>Profile</button><HeaderNavMenu variant="landing" onPickLegal={onPickLegal} onPickMission={onPickMission} onPickSupport={()=>{}}/><button className="faq-pill" onClick={onSignOut}>Sign out</button></>:<><button className="faq-pill" onClick={onSignIn}>Sign in</button><button className="faq-pill red" onClick={onSignUp}>Create account</button></>}</div></header><main className="support-content"><aside><h1>Support</h1><p>We&apos;re here to help. Find answers to common questions, troubleshooting tips, and ways to get in touch with our team.</p><label className="support-search"><span>⌕</span><input placeholder="Search for help..."/></label><section className="support-contact"><div className="support-contact-title"><span>✉</span><h2>Contact us</h2></div><p>For account help, privacy requests, technical issues, or general questions, email us at:</p>{mailto?<a href={mailto}>{email}</a>:<b>{email}</b>}<p>We aim to reply within a few business days.</p><hr/><h3>Other ways to reach us</h3><p><strong>𝕏 (Twitter)</strong><br/>@HotTakeDebate</p><p><strong>Instagram</strong><br/>@HotTakeDebate</p><p><strong>Feedback &amp; Suggestions</strong><br/>Help us improve Hot Take</p></section></aside><div className="support-list">{items.map(([icon,title,copy])=><article key={title}><span><SupportIcon type={icon}/></span><div><h2>{title}</h2><p>{copy}</p>{icon==='question'&&<button onClick={onPickFaq}>View FAQ</button>}</div><i>⌄</i></article>)}</div></main><div className="support-bottom">Still need help? Email us at {mailto?<a href={mailto}>{email}</a>:<b>{email}</b>} and we&apos;ll get back to you.</div><footer className="faq-footer"><HotTakeWordmark variant="footer"/><p>&copy; 2026 Hot Take Debate. All rights reserved.</p><div><span>Follow us</span><a href="https://x.com" aria-label="X"><IconX/></a><a href="https://instagram.com" aria-label="Instagram"><IconInstagram/></a><a href="https://reddit.com" aria-label="Reddit"><IconReddit/></a><a href="https://youtube.com" aria-label="YouTube"><IconYouTube/></a></div></footer></div>}
